-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE `CAR_CARGO_GRADUACAO` (
`CAR_ID` INT(3) PRIMARY KEY,
`CAR_DESCRICAO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `UNI_UNIDADE_OPERACIONAL` (
`UNI_FONE` VARCHAR(20),
`UNI_LOCAL` VARCHAR(64),
`UNI_DESCRICAO` VARCHAR(50),
`UNI_ID` INT(11) PRIMARY KEY,
`ORG_ID` INT(5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ORG_ORGAO` (
`ORG_ID` INT(5) PRIMARY KEY,
`ORG_DESCRICAO` VARCHAR(50),
`ORG_TELEFONE` VARCHAR(20),
`ORG_CNPJ` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ENV_ENVOLVIMENTO_AGENTE` (
`ENV_ID` INT(2) PRIMARY KEY,
`ENV_DESCRICAO` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MODUS_OPERANDI` (
`MOD_ID` INT(11) PRIMARY KEY,
`MOD_FORMA_APROXIMACAO` VARCHAR(20),
`MOD_FORMA_ACAO_ABORDAGEM` VARCHAR(30),
`MOD_LOCAL_ENTRADA` VARCHAR(30),
`MOD_FORMA_ENTRADA` VARCHAR(30),
`MOD_ALTERACOES_NO_LOCAL` ENUM('S','N'),
`MOD_FORMA_DE_EVASAO` VARCHAR(30),
`MOD_CRIMES_SEXUAIS` ENUM('S','N'),
`MOD_ESTELIONATO` ENUM('S','N')
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `AGE_AGENTE` (
`DATA_NASCIMENTO` DATE,
`AGE_MATRICULA` INT(11),
`AGE_NOME` VARCHAR(64),
`AGE_ID` INT(11) PRIMARY KEY,
`CAR_ID` INT(3),
FOREIGN KEY(`CAR_ID`) REFERENCES `CAR_CARGO_GRADUACAO` (`CAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `TEL_TELEFONE` (
`TEL_ID` INT(11) PRIMARY KEY,
`TEL_NUMERO` INT(11),
`ENV_ID` INT(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `END_ENDERECO` (
`END_ID` INT(11) PRIMARY KEY,
`END_LOGRADOURO` VARCHAR(64),
`END_CEP` INT(8),
`END_MUNICIPIO` VARCHAR(30),
`END_UF` VARCHAR(2),
`END_PONTO_REFERENCIA` VARCHAR(30),
`END_COMPLEMENTO` VARCHAR(20),
`END_NUM` INT(4),
`END_BAIRRO` VARCHAR(30),
`ENV_ID` INT(11)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `VEI_VEICULO` (
`VEI_COR` VARCHAR(15),
`VEI_RENAVAM` VARCHAR(20),
`VEI_UF` VARCHAR(2),
`VEI_CHASSI` VARCHAR(20),
`VEI_PLACA` VARCHAR(7),
`VEI_APREENDIDO` ENUM('S','N'),
`VEI_MOTIVO_DO_REGISTRO` VARCHAR(64),
`VEI_ID` INT(11) PRIMARY KEY,
`VEI_MARCA_MODELO` VARCHAR(20),
`VEI_ANO` YEAR
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `OBJ_OBJETO` (
`OBJ_ID` INT(11) PRIMARY KEY,
`OBJ_TIPO` VARCHAR(20),
`OBJ_VALOR` FLOAT,
`OBJ_APREENDIDO` ENUM('S','N'),
`OBJ_NUM_SERIE` VARCHAR(20),
`OBJ_MARCA_MODELO` VARCHAR(20),
`OBJ_MOEDA` VARCHAR(3),
`OBJ_QUANTIDADE` INT(5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ROP` (
`ROP_ID` INT(11) PRIMARY KEY,
`ROP_CD_NUM_OCORRENCIA` INT,
`ROP_CD_CIRCUNSCRICAO` INT,
`ROP_DH_REGISTRO` TIMESTAMP,
`ROP_BI_CRIME_CONSUMADO` ENUM('S','N'),
`ROP_BI_CRIME_DOLOSO` ENUM('S','N'),
`ROP_BI_AUTORIA_CONHECIDA` ENUM('C','D'),
`ROP_BI_FLAGRANTE` ENUM('S','N'),
`ROP_DS_VIATURA` VARCHAR(30),
`ROP_DS_DA_NATUREZA` VARCHAR(50),
`ROP_DS_DADOS_COMPLEMENTARES` VARCHAR(512),
`ROP_DS_LOCAL_PRINCIPAL_OCORRENCIA` VARCHAR(30),
`ROP_CD_CIRCUNSCRICAO_FATO` VARCHAR(30),
`ROP_DT_DO_FATO` DATE,
`ROP_HR_DO_FATO` TIME,
`MOD_ID` INT(11),
`END_ID` INT(11),
FOREIGN KEY(`MOD_ID`) REFERENCES `MODUS_OPERANDI` (`MOD_ID`),
FOREIGN KEY(`END_ID`) REFERENCES `END_ENDERECO` (`END_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ENV_ENVOLVIDO` (
`ENV_ID` INT(11) PRIMARY KEY,
`ENV_CPF` VARCHAR(11),
`ENV_RG` VARCHAR(20),
`ENV_RG_ORGAO_EXP` VARCHAR(32),
`ENV_CNH` VARCHAR(20),
`ENV_NOME_PAI` VARCHAR(64),
`ENV_NOME_MAE` VARCHAR(64),
`ENV_SEXO` ENUM('M','F'),
`ENV_APELIDO` VARCHAR(30),
`ENV_TIPO` ENUM('F','J'),
`ENV_DATA_NASCIMENTO` DATE,
`ENV_NOME_RAZAO_SOCIAL` VARCHAR(64),
`ENV_BIGODE` ENUM('S','N'),
`ENV_CABELO_TIPO_COR` VARCHAR(30),
`ENV_TIPO_CICATRIZ` VARCHAR(30),
`ENV_DEFEITO_FISICO` VARCHAR(30),
`ENV_BARBA` VARCHAR(20),
`ENV_TIPO_DENTES` VARCHAR(30),
`ENV_TATUAGEM` VARCHAR(30),
`ENV_COR_PELE` INT(1),
`ENV_ESTADO_CIVIL` INT(1),
`ENV_ESCOLARIDADE` INT(1),
`ENV_IDADE_APARENTE` INT(1),
`ENV_NATURALIDADE` VARCHAR(30),
`ENV_PESO` INT(1),
`ENV_ALTURA_APARENTE` INT(1),
`ENV_TURISTA` ENUM('S','N')
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ENVOLVIMENTO_CARACTERISTICAS_ROP` (
`ROP_ID` INT(11),
`ENV_ID` INT(11),
`ENV_CAR_ID` INT(11) PRIMARY KEY,
`ENV_ESCOLARIDADE` INT(1),
`ENV_ESTADO_CIVIL` INT(1),
`ENV_PESO` INT(1),
`ENV_ALTURA_APARENTE` INT(1),
`ENV_IDADE_APARENTE` INT(1),
`ENV_TIPO_ENVOLVIMENTO` INT(1),
FOREIGN KEY(`ROP_ID`) REFERENCES `ROP` (`ROP_ID`),
FOREIGN KEY(`ENV_ID`) REFERENCES `ENV_ENVOLVIDO` (`ENV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `UNIDADE_AGENTE` (
`UNI_ID` INT(11),
`AGE_ID` INT(11),
`UNI_AGENTE_ID` INT(11) PRIMARY KEY,
`UNI_DATA_ENTRADA` DATE,
`UNI_DATA_SAIDA` DATE,
FOREIGN KEY(`UNI_ID`) REFERENCES `UNI_UNIDADE_OPERACIONAL` (`UNI_ID`),
FOREIGN KEY(`AGE_ID`) REFERENCES `AGE_AGENTE` (`AGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `PARTICIPA` (
`ROP_ID` INT(11),
`AGE_ID` INT(11),
`ENV_ID` INT(2),
PRIMARY KEY(`ROP_ID`,`AGE_ID`,`ENV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `VEICULO_ENVOLVIDO_ROP` (
`VER_CD_ENVOLVIMENTO` INT(11),
`ENV_ID` INT(11),
`ROP_ID` INT(11),
`VEI_ID` INT(11),
PRIMARY KEY(`ENV_ID`,`ROP_ID`,`VEI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `POSSUI` (
`OBJ_ID` INT(11),
`ENV_ID` INT(11),
`ROP_ID` INT(11),
PRIMARY KEY(`OBJ_ID`,`ENV_ID`,`ROP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `UNI_UNIDADE_OPERACIONAL` 
	ADD FOREIGN KEY(`ORG_ID`) REFERENCES `ORG_ORGAO` (`ORG_ID`);
ALTER TABLE `TEL_TELEFONE` 
    ADD FOREIGN KEY(`ENV_ID`) REFERENCES `ENV_ENVOLVIDO` (`ENV_ID`);
ALTER TABLE `END_ENDERECO` 
    ADD FOREIGN KEY(`ENV_ID`) REFERENCES `ENV_ENVOLVIDO` (`ENV_ID`);
